### ISSUE TITLE
Feature Request: Filament Admin Integration

### ISSUE THREAD

**Issue by MACscr** [andreaselia/laravel-analytics#29]
Are you familiar with Filament Admin panel? Its an solid open source alternative to Nova. Ive been using it myself for projects for about a year now and its gotten pretty popular. Have you considered making package for its panel so that users can use its UI and widgets to view the analytics data? Would be pretty awesome.

Side question: How does the analytics gathering work when caching and proxy services like Cloudflare are you used? I think thats why most solutions are javascript these days.

**Comment by andreaselia** [comment]
Hi @MACscr,

I hadn't thought of a Filament Admin Panel contribution for this package, but that could be a pretty cool idea. Would you like to help out? If so, I've made a start [here](https://github.com/andreaselia/filament-laravel-analytics), but no worries if not, I'll have a play around with it.

**Comment by MACscr** [comment]
Thanks for looking into it. You wont regret getting into Filament. i really like it. They have an awesome discord server. 

Wife and I are expecting our second child this week, so don't have a lot of free time at the moment. LOL

Any chance you could respond to my "side question"?

**Comment by andreaselia** [comment]
> Thanks for looking into it. You wont regret getting into Filament. i really like it. They have an awesome discord server.
> 
> Wife and I are expecting our second child this week, so don't have a lot of free time at the moment. LOL
> 
> Any chance you could respond to my "side question"?

Appreciate that! No worries, being part of a large family I know the toll it takes, wishing you both all the best.

My apologies, I knew I forgot something but couldn't put my finger on what. I actually haven't tested the analytics with a proxy service, so I'm not entirely sure what the outcome would be, but it's something probably worth testing out and documenting at some point.

@justRau recently added a way for users to implement their own ways of tracking analytics, so that's always an option for people using the package too, should they run into issues with the default method of sessions.

**Comment by andreaselia** [comment]
Going to close this as it's not really an issue for this, and the Filament package has been started. Contributions to both are welcome by anyone who may read this.
